In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import KFold, StratifiedKFold
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

In [7]:
digits = load_digits()
kf = KFold(n_splits=3)
skf = StratifiedKFold(n_splits=3)

In [3]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [8]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [30]:
scores_logReg = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                        digits.target[train_index], digits.target[test_index]
    scores_logReg.append(get_score(LogisticRegression(solver="sag"), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(C=10,kernel="linear"), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

C:\Users\OWNER1\anaconda3\lib\site-packages\sklearn\linear_model\_sag.py:352: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\OWNER1\anaconda3\lib\site-packages\sklearn\linear_model\_sag.py:352: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\OWNER1\anaconda3\lib\site-packages\sklearn\linear_model\_sag.py:352: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


In [31]:
scores_logReg

[0.9282136894824707, 0.9398998330550918, 0.9181969949916527]

In [32]:
scores_svm

[0.9348914858096828, 0.9565943238731218, 0.9398998330550918]

In [33]:
scores_rf

[0.9232053422370617, 0.9449081803005008, 0.9215358931552587]

In [34]:
from sklearn.model_selection import cross_val_score

In [36]:
cross_val_score(LogisticRegression(solver="sag"), digits.data, digits.target)

C:\Users\OWNER1\anaconda3\lib\site-packages\sklearn\linear_model\_sag.py:352: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\OWNER1\anaconda3\lib\site-packages\sklearn\linear_model\_sag.py:352: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\OWNER1\anaconda3\lib\site-packages\sklearn\linear_model\_sag.py:352: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\OWNER1\anaconda3\lib\site-packages\sklearn\linear_model\_sag.py:352: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\OWNER1\anaconda3\lib\site-packages\sklearn\linear_model\_sag.py:352: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


array([0.925     , 0.86111111, 0.94428969, 0.95264624, 0.90250696])

In [39]:
cross_val_score(SVC(C=10), digits.data, digits.target)

array([0.98055556, 0.95833333, 0.98328691, 0.98885794, 0.95821727])

In [41]:
cross_val_score(RandomForestClassifier(n_estimators=200), digits.data, digits.target)

array([0.94722222, 0.91666667, 0.95821727, 0.97214485, 0.92479109])